Allow additions to ignore list even while unremovable users present
Awful/Awful.app pull request #1160
Opened 2022-12-04 04:18 UTC by dfsm

- Function addUserToIgnoreList updated to take a userid and make POST to member2.php using parameters appropriate for the Profile (member.php) page.
- Fixed context menu to say "Ignore/Unignore user" conditionally
- Updated IgnoreListChangeScrapeResult.swift to add a success message produced by the forums. There's different text on the response page while adding an ignored user via profile vs ignore list

See:
https://forums.somethingawful.com/showthread.php?threadid=3910071&pagenumber=104#post528132223

Tested:
- Adding user to ignore list: OK
- Removing user from ignore list (which uses the same method as before): OK
- Adding a mod to the ignore list: Error as expected

2022-12-05 06:14 UTC, nolanw requested changes
I don't think `formkey` works like this :)

2022-12-05 06:14 UTC, nolanw commented on App/View Controllers/Posts/PostsPageViewController.swift
> +            // removing ignored users requires username. adding a new user requires userid
lol

2022-12-05 06:14 UTC, nolanw commented on AwfulCore/Sources/AwfulCore/Networking/ForumsClient.swift
> +            "formkey": "c171e9239a0684719b61b943b7e3e091",
I expect this is different for each user (or session, or similar), so it's not appropriate to hardcode it. The former approach scrapes it from the form, we should do the same here.

2022-12-11 00:19 UTC, dfsm commented on App/View Controllers/Posts/PostsPageViewController.swift
> +            // removing ignored users requires username. adding a new user requires userid
lol

2022-12-11 20:08 UTC, merged